import type { Metadata } from 'next'
import '../styles/global.css'
import GlobalHeader from '@/components/GlobalHeader'
import GlobalFooter from '@/components/GlobalFooter'

export const metadata: Metadata = {
  title: '말터 | 우리 아이 언어발달, 어디서 시작할지 막막하다면',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/logos/malterPurple.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalHeader />
        <main>{children}</main>
        <GlobalFooter />
      </body>
    </html>
  )
}
